name: Pecureo
favicon: null
layout_spectrum: 0.23593274969607592
typography_spectrum: 0.3356950031593442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.19054582784883678
  lightness: 0.7670584490988404
  saturation: 0.249364806804806
  rhythmicContrast: 0.7532686530612409
purpose: []
